name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY_B64 }}" | base64 --decode > key.pem
          chmod 600 key.pem
      
      - name: SSH, Pull & Deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
              cd /home/ubuntu/open-search
              git pull
              docker compose pull
              docker compose up -d
            EOF