name: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: frontend
            context: .
            dockerfile: ./frontend/client/frontend.Dockerfile
          - service: api
            context: .
            dockerfile: ./backend/cmd/api/api.Dockerfile
          - service: crawler
            context: .
            dockerfile: ./backend/cmd/crawler/crawler.Dockerfile
          - service: indexer
            context: .
            dockerfile: ./backend/cmd/indexer/indexer.Dockerfile
          - service: pagerank
            context: .
            dockerfile: ./backend/cmd/pagerank/pagerank.Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: aliosman0/${{ matrix.service }}:latest